
import { JobOffer } from '../types';

export const MOCK_OFFERS: JobOffer[] = [
  {
    id: '1',
    title: 'Senior Frontend Engineer',
    salaryMin: 85000,
    salaryMax: 110000,
    salaryCurrency: 'USD',
    workMode: 'Remote',
    techStack: ['React', 'TypeScript', 'Node.js', 'AWS'],
    experienceLevel: 'Senior',
    contractType: 'Full-time',
    benefits: ['Health Insurance', 'Unlimited PTO', 'Home Office Stipend'],
    createdAt: '2024-03-20T10:00:00Z',
    tags: ['Frontend', 'Backend'],
    sourceName: 'LinkedIn',
    sourceUrl: 'https://linkedin.com/jobs/view/1',
    languages: [{ name: 'English', level: 'C1' }]
  },
  {
    id: '2',
    title: 'Fullstack Laravel Developer',
    salaryMin: 70000,
    salaryMax: 90000,
    salaryCurrency: 'USD',
    workMode: 'Hybrid',
    location: 'Madrid, ES',
    techStack: ['Vue.js', 'PHP', 'Laravel', 'MySQL'],
    experienceLevel: 'Mid',
    contractType: 'Full-time',
    benefits: ['Free Lunch', 'Gym Membership', 'Bono Anual'],
    createdAt: '2024-03-19T14:30:00Z',
    tags: ['Fullstack'],
    sourceName: 'Indeed',
    sourceUrl: 'https://indeed.com/viewjob?jk=2',
    languages: [{ name: 'Spanish', level: 'Native' }, { name: 'English', level: 'B2' }]
  },
  {
    id: '3',
    title: 'Lead React Native Architect',
    salaryMin: 120000,
    salaryMax: 150000,
    salaryCurrency: 'EUR',
    workMode: 'Remote',
    techStack: ['React', 'Next.js', 'Tailwind', 'PostgreSQL'],
    experienceLevel: 'Lead',
    contractType: 'Full-time',
    benefits: ['Stock Options', 'Education Budget', '4-day Work Week'],
    createdAt: '2024-03-21T09:15:00Z',
    tags: ['Frontend'],
    sourceName: 'Glassdoor',
    sourceUrl: 'https://glassdoor.com/job-listing/3',
    languages: [{ name: 'English', level: 'C2' }]
  },
  {
    id: '4',
    title: 'Backend Java Engineer',
    salaryMin: 60000,
    salaryMax: 80000,
    salaryCurrency: 'USD',
    workMode: 'On-site',
    location: 'Barcelona, ES',
    techStack: ['Java', 'Spring Boot', 'Kubernetes'],
    experienceLevel: 'Mid',
    contractType: 'Contract',
    benefits: ['Health Insurance', 'Public Transport Pass'],
    createdAt: '2024-03-18T16:45:00Z',
    tags: ['Backend', 'DevOps'],
    sourceName: 'GetOnBoard',
    sourceUrl: 'https://getonbrd.com/jobs/4',
    languages: [{ name: 'English', level: 'B1' }]
  },
  {
    id: '5',
    title: 'Senior Python Developer',
    salaryMin: 95000,
    salaryMax: 130000,
    salaryCurrency: 'USD',
    workMode: 'Remote',
    techStack: ['Python', 'Django', 'React', 'Docker'],
    experienceLevel: 'Senior',
    contractType: 'Full-time',
    benefits: ['Flexible Hours', 'Mental Health Support'],
    createdAt: '2024-03-22T08:00:00Z',
    tags: ['Fullstack'],
    sourceName: 'We Work Remotely',
    sourceUrl: 'https://weworkremotely.com/jobs/5',
    languages: [{ name: 'English', level: 'C1' }]
  },
  {
    id: '6',
    title: 'DevOps Engineer',
    salaryMin: 100000,
    salaryMax: 140000,
    salaryCurrency: 'USD',
    workMode: 'Remote',
    techStack: ['Terraform', 'Kubernetes', 'AWS', 'Python'],
    experienceLevel: 'Senior',
    contractType: 'Full-time',
    benefits: ['Remote Setup', 'Profit Sharing'],
    createdAt: '2024-03-23T11:00:00Z',
    tags: ['DevOps'],
    sourceName: 'RemoteOK',
    sourceUrl: 'https://remoteok.com/remote-jobs/6',
    languages: [{ name: 'English', level: 'C1' }]
  },
  {
    id: '7',
    title: 'Data Scientist',
    salaryMin: 110000,
    salaryMax: 160000,
    salaryCurrency: 'USD',
    workMode: 'Remote',
    techStack: ['Python', 'PyTorch', 'SQL', 'Scikit-learn'],
    experienceLevel: 'Senior',
    contractType: 'Full-time',
    benefits: ['Conference Budget', 'Health Plan'],
    createdAt: '2024-03-24T09:00:00Z',
    tags: ['Data'],
    sourceName: 'Dice',
    sourceUrl: 'https://dice.com/jobs/7',
    languages: [{ name: 'English', level: 'B2' }]
  },
  {
    id: '8',
    title: 'Junior Web Developer',
    salaryMin: 40000,
    salaryMax: 55000,
    salaryCurrency: 'USD',
    workMode: 'On-site',
    location: 'Berlin, DE',
    techStack: ['JavaScript', 'HTML', 'CSS'],
    experienceLevel: 'Junior',
    contractType: 'Full-time',
    benefits: ['Mentorship Program', 'Language Courses'],
    createdAt: '2024-03-25T14:00:00Z',
    tags: ['Frontend'],
    sourceName: 'StepStone',
    sourceUrl: 'https://stepstone.de/jobs/8',
    languages: [{ name: 'German', level: 'B2' }, { name: 'English', level: 'B1' }]
  },
  {
    id: '9',
    title: 'Staff Security Engineer',
    salaryMin: 160000,
    salaryMax: 220000,
    salaryCurrency: 'USD',
    workMode: 'Remote',
    techStack: ['Go', 'Rust', 'Cloud Security'],
    experienceLevel: 'Staff',
    contractType: 'Full-time',
    benefits: ['RSUs', 'Unlimited Vacation'],
    createdAt: '2024-03-26T10:30:00Z',
    tags: ['Security', 'Backend'],
    sourceName: 'HackerNews',
    sourceUrl: 'https://news.ycombinator.com/item?id=9',
    languages: [{ name: 'English', level: 'C2' }]
  },
  {
    id: '10',
    title: 'Mobile Developer (iOS)',
    salaryMin: 80000,
    salaryMax: 120000,
    salaryCurrency: 'USD',
    workMode: 'Hybrid',
    location: 'London, UK',
    techStack: ['Swift', 'SwiftUI', 'CoreData'],
    experienceLevel: 'Senior',
    contractType: 'Full-time',
    benefits: ['Private Healthcare', 'Cycle to Work'],
    createdAt: '2024-03-27T15:20:00Z',
    tags: ['Mobile'],
    sourceName: 'Reed',
    sourceUrl: 'https://reed.co.uk/jobs/10',
    languages: [{ name: 'English', level: 'Native' }]
  },
  {
    id: '11',
    title: 'Mid-level Go Developer',
    salaryMin: 75000,
    salaryMax: 95000,
    salaryCurrency: 'USD',
    workMode: 'Remote',
    techStack: ['Go', 'gRPC', 'PostgreSQL'],
    experienceLevel: 'Mid',
    contractType: 'Full-time',
    benefits: ['Learning Budget', 'Fitness Stipend'],
    createdAt: '2024-03-28T12:00:00Z',
    tags: ['Backend'],
    sourceName: 'Golang Projects',
    sourceUrl: 'https://golangprojects.com/job/11',
    languages: [{ name: 'English', level: 'B2' }]
  },
  {
    id: '12',
    title: 'Cloud Architect',
    salaryMin: 140000,
    salaryMax: 180000,
    salaryCurrency: 'USD',
    workMode: 'Hybrid',
    location: 'Paris, FR',
    techStack: ['Azure', 'Terraform', 'Security'],
    experienceLevel: 'Lead',
    contractType: 'Full-time',
    benefits: ['Company Car', 'Meal Vouchers'],
    createdAt: '2024-03-29T16:10:00Z',
    tags: ['DevOps', 'Cloud'],
    sourceName: 'Welcome to the Jungle',
    sourceUrl: 'https://welcometothejungle.com/jobs/12',
    languages: [{ name: 'French', level: 'C1' }, { name: 'English', level: 'C1' }]
  },
  {
    id: '13',
    title: 'React Developer',
    salaryMin: 65000,
    salaryMax: 85000,
    salaryCurrency: 'EUR',
    workMode: 'Remote',
    techStack: ['React', 'Redux', 'Jest'],
    experienceLevel: 'Mid',
    contractType: 'Full-time',
    benefits: ['Work from Anywhere', 'Stock Options'],
    createdAt: '2024-03-30T08:45:00Z',
    tags: ['Frontend'],
    sourceName: 'Ottta',
    sourceUrl: 'https://otta.com/jobs/13',
    languages: [{ name: 'English', level: 'B2' }]
  },
  {
    id: '14',
    title: 'Machine Learning Engineer',
    salaryMin: 125000,
    salaryMax: 175000,
    salaryCurrency: 'USD',
    workMode: 'Remote',
    techStack: ['Python', 'TensorFlow', 'Kubeflow'],
    experienceLevel: 'Senior',
    contractType: 'Full-time',
    benefits: ['Research Days', 'Remote Stipend'],
    createdAt: '2024-03-31T11:30:00Z',
    tags: ['AI/ML'],
    sourceName: 'AngelList',
    sourceUrl: 'https://wellfound.com/jobs/14',
    languages: [{ name: 'English', level: 'C1' }]
  },
  {
    id: '15',
    title: 'QA Automation Engineer',
    salaryMin: 70000,
    salaryMax: 90000,
    salaryCurrency: 'USD',
    workMode: 'Remote',
    techStack: ['Cypress', 'Playwright', 'TypeScript'],
    experienceLevel: 'Mid',
    contractType: 'Contract',
    benefits: ['Flexible Hours'],
    createdAt: '2024-04-01T10:00:00Z',
    tags: ['QA'],
    sourceName: 'Monster',
    sourceUrl: 'https://monster.com/job/15',
    languages: [{ name: 'English', level: 'B2' }]
  }
];
